export const FELLOWSHIP_EVENT = {
  DUNGEON_END: "DUNGEON_END",
  DUNGEON_START: "DUNGEON_START",
  ENCOUNTER_END: "ENCOUNTER_END",
  ENCOUNTER_START: "ENCOUNTER_START",
  LOGGING_STARTED: "LOGGING_STARTED",
  MAP_CHANGE: "MAP_CHANGE",
  UNIT_DEATH: "UNIT_DEATH",
  ZONE_CHANGE: "ZONE_CHANGE",
} as const;

export type FellowshipEventType =
  (typeof FELLOWSHIP_EVENT)[keyof typeof FELLOWSHIP_EVENT];

export const fellowshipEventTypes = Object.values(FELLOWSHIP_EVENT);
